#### Creation of Matrix

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [6]:
M = np.array([[3,4],[2,8],[1,9]])

In [7]:
M

array([[3, 4],
       [2, 8],
       [1, 9]])

In [17]:
M.shape

(3, 2)

In [18]:
M.min()

1

In [19]:
type(M)

numpy.ndarray

In [20]:
M.size

6

In [21]:
v = np.array([4,6,5,3,1,7,6,3])

In [22]:
v.size

8

In [23]:
v.reshape(4, 2)

array([[4, 6],
       [5, 3],
       [1, 7],
       [6, 3]])

In [24]:
v.reshape(2,4)

array([[4, 6, 5, 3],
       [1, 7, 6, 3]])

In [25]:
v.reshape(1,8)

array([[4, 6, 5, 3, 1, 7, 6, 3]])

In [26]:
v.reshape(3,3)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [27]:
M.dtype

dtype('int64')

In [28]:
M = np.array([[3,4],[2,8],[1,9]], dtype=np.int8)

In [29]:
M

array([[3, 4],
       [2, 8],
       [1, 9]], dtype=int8)

In [30]:
M = np.array([[3,4,8,0],[2,8,1,3],[1,9,5,6]], dtype=np.int8)

In [31]:
M

array([[3, 4, 8, 0],
       [2, 8, 1, 3],
       [1, 9, 5, 6]], dtype=int8)

In [32]:
M.flatten()

array([3, 4, 8, 0, 2, 8, 1, 3, 1, 9, 5, 6], dtype=int8)

In [33]:
M.reshape(-1,3)

array([[3, 4, 8],
       [0, 2, 8],
       [1, 3, 1],
       [9, 5, 6]], dtype=int8)

In [34]:
M.reshape(-1,2)

array([[3, 4],
       [8, 0],
       [2, 8],
       [1, 3],
       [1, 9],
       [5, 6]], dtype=int8)

In [35]:
M.reshape(2,-1)

array([[3, 4, 8, 0, 2, 8],
       [1, 3, 1, 9, 5, 6]], dtype=int8)

In [36]:
M.reshape(-1)

array([3, 4, 8, 0, 2, 8, 1, 3, 1, 9, 5, 6], dtype=int8)

#### Matrix Operations

In [40]:
M

array([[3, 4, 8, 0],
       [2, 8, 1, 3],
       [1, 9, 5, 6]], dtype=int8)

In [41]:
M[1][2]

1

In [42]:
for row in M:
    print(row)

[3 4 8 0]
[2 8 1 3]
[1 9 5 6]


In [45]:
for row in M:
    for value in row:
        print(value, end=' ')
    print()

3 4 8 0 
2 8 1 3 
1 9 5 6 


##### Addition

In [48]:
M1 = np.array([[4,5,6],[2,1,9],[0,2,8]])
M2 = np.array([[2,5,7],[0,8,7],[6,4,3]])

In [49]:
M3 = M1 + M2

In [50]:
M3

array([[ 6, 10, 13],
       [ 2,  9, 16],
       [ 6,  6, 11]])

##### Subtraction

In [52]:
M3 = M1 - M2

In [53]:
M3

array([[ 2,  0, -1],
       [ 2, -7,  2],
       [-6, -2,  5]])

In [54]:
M1

array([[4, 5, 6],
       [2, 1, 9],
       [0, 2, 8]])

##### Scaler Multiplication

In [57]:
M1, M1 * 2

(array([[4, 5, 6],
        [2, 1, 9],
        [0, 2, 8]]),
 array([[ 8, 10, 12],
        [ 4,  2, 18],
        [ 0,  4, 16]]))

In [58]:
M1 + 10

array([[14, 15, 16],
       [12, 11, 19],
       [10, 12, 18]])

In [61]:
M3 = 2 * (M1 + M2)

In [62]:
M4 = 2 * M1 + 2 * M2

In [63]:
M3, M4

(array([[12, 20, 26],
        [ 4, 18, 32],
        [12, 12, 22]]),
 array([[12, 20, 26],
        [ 4, 18, 32],
        [12, 12, 22]]))

In [65]:
(2 + 3) * M1

array([[20, 25, 30],
       [10,  5, 45],
       [ 0, 10, 40]])

In [66]:
2 * M1 + 3 * M1

array([[20, 25, 30],
       [10,  5, 45],
       [ 0, 10, 40]])

In [67]:
1 * M1

array([[4, 5, 6],
       [2, 1, 9],
       [0, 2, 8]])

In [68]:
-1 * M1

array([[-4, -5, -6],
       [-2, -1, -9],
       [ 0, -2, -8]])

##### Matrix Multiplication

In [70]:
M1, M2

(array([[4, 5, 6],
        [2, 1, 9],
        [0, 2, 8]]),
 array([[2, 5, 7],
        [0, 8, 7],
        [6, 4, 3]]))

In [71]:
M1 * M2

array([[ 8, 25, 42],
       [ 0,  8, 63],
       [ 0,  8, 24]])

In [72]:
M1 @ M2

array([[44, 84, 81],
       [58, 54, 48],
       [48, 48, 38]])

In [74]:
M2 @ M1

array([[ 18,  29, 113],
       [ 16,  22, 128],
       [ 32,  40,  96]])

In [75]:
M3

array([[12, 20, 26],
       [ 4, 18, 32],
       [12, 12, 22]])

In [76]:
M1 @ (M2 @ M3), (M1 @ M2) @ M3

(array([[1836, 3364, 5614],
        [1488, 2708, 4292],
        [1224, 2280, 3620]]),
 array([[1836, 3364, 5614],
        [1488, 2708, 4292],
        [1224, 2280, 3620]]))

In [77]:
np.matmul(M1, M2)

array([[44, 84, 81],
       [58, 54, 48],
       [48, 48, 38]])

##### Matrix Transpose

In [79]:
M1.T

array([[4, 2, 0],
       [5, 1, 2],
       [6, 9, 8]])

In [80]:
M1

array([[4, 5, 6],
       [2, 1, 9],
       [0, 2, 8]])

In [81]:
np.transpose(M1)

array([[4, 2, 0],
       [5, 1, 2],
       [6, 9, 8]])

In [84]:
rows = int(input('Enter number of rows: '))
cols = int(input('Enter number of columns: '))
mat = np.zeros(rows * cols, dtype = np.int16)
for i in range(len(mat)):
    mat[i] = int(input('Enter value: '))

mat = mat.reshape(rows, cols)
print('Matrix:\n', mat)
print('Transpose:\n', mat.T)

Enter number of rows:  3
Enter number of columns:  2
Enter value:  5
Enter value:  4
Enter value:  6
Enter value:  7
Enter value:  8
Enter value:  9


Matrix:
 [[5 4]
 [6 7]
 [8 9]]
Transpose:
 [[5 6 8]
 [4 7 9]]


In [86]:
M1.T.T

array([[4, 5, 6],
       [2, 1, 9],
       [0, 2, 8]])

In [87]:
M1

array([[4, 5, 6],
       [2, 1, 9],
       [0, 2, 8]])

In [88]:
M1.T + M2.T, (M1 + M2).T

(array([[ 6,  2,  6],
        [10,  9,  6],
        [13, 16, 11]]),
 array([[ 6,  2,  6],
        [10,  9,  6],
        [13, 16, 11]]))

In [91]:
(M1 @ M2).T,    M2.T @ M1.T

(array([[44, 58, 48],
        [84, 54, 48],
        [81, 48, 38]]),
 array([[44, 58, 48],
        [84, 54, 48],
        [81, 48, 38]]))

##### Trace of Matrix

In [93]:
M1

array([[4, 5, 6],
       [2, 1, 9],
       [0, 2, 8]])

In [97]:
add = 0
rn = 0
for row in M1:
    add = add + row[rn]
    rn += 1

In [98]:
add

13

In [99]:
np.trace(M1)

13

In [100]:
M3 = np.array([[3,4,8,0],[2,8,1,3],[1,9,5,6]], dtype=np.int8)

In [101]:
M3

array([[3, 4, 8, 0],
       [2, 8, 1, 3],
       [1, 9, 5, 6]], dtype=int8)

In [102]:
np.trace(M3)

16

In [103]:
M1 @ M2

array([[44, 84, 81],
       [58, 54, 48],
       [48, 48, 38]])

In [104]:
M2 @ M1

array([[ 18,  29, 113],
       [ 16,  22, 128],
       [ 32,  40,  96]])

In [105]:
np.trace(M1 @ M2), np.trace(M2 @ M1) 

(136, 136)

In [106]:
np.trace(M1), np.trace(M1.T)

(13, 13)

In [108]:
2 * np.trace(M1), np.trace(2 * M1), 

(26, 26)

##### Determinant of Matrix

In [110]:
M1

array([[4, 5, 6],
       [2, 1, 9],
       [0, 2, 8]])

In [111]:
np.linalg.det(M1)

-95.99999999999999

In [112]:
np.linalg.det(M2)

-133.99999999999997

In [113]:
4 * (8*1-9*2) - 5 * (8*2-9*0) + 6 * (2*2-0*1)

-96

In [114]:
M1

array([[4, 5, 6],
       [2, 1, 9],
       [0, 2, 8]])

##### Inverse of the Matrix

In [116]:
np.linalg.inv(M1)

array([[ 0.10416667,  0.29166667, -0.40625   ],
       [ 0.16666667, -0.33333333,  0.25      ],
       [-0.04166667,  0.08333333,  0.0625    ]])

##### Rank of the Matrix

In [119]:
M4 = np.array([[1,2],[2,4]])

In [120]:
M4

array([[1, 2],
       [2, 4]])

In [121]:
np.linalg.matrix_rank(M4)

1

In [122]:
M5 = np.array([[1,2],[3,4]])
np.linalg.matrix_rank(M5)

2

In [124]:
M5

array([[1, 2],
       [3, 4]])

In [131]:
M4 = np.array([[1,2,3],[2,4,6],[1.5,3.0,4.5]])
np.linalg.matrix_rank(M4)

1

In [132]:
M4

array([[1. , 2. , 3. ],
       [2. , 4. , 6. ],
       [1.5, 3. , 4.5]])

In [133]:
M4 = np.array([[1,2,3],[2,4,6],[7,8,9]])
np.linalg.matrix_rank(M4)

2

In [134]:
M4[0]

array([1, 2, 3])

In [135]:
M4[0] * 2

array([2, 4, 6])

In [136]:
M4[0] * 1.5

array([1.5, 3. , 4.5])

##### Row Matrix

In [138]:
M1

array([[4, 5, 6],
       [2, 1, 9],
       [0, 2, 8]])

In [143]:
R=M1.reshape(1,-1)

In [144]:
R.shape

(1, 9)

In [141]:
R

array([[4, 5, 6, 2, 1, 9, 0, 2, 8]])

##### Column Matrix

In [146]:
C = M1.reshape(-1, 1)

In [147]:
C

array([[4],
       [5],
       [6],
       [2],
       [1],
       [9],
       [0],
       [2],
       [8]])

In [148]:
C.shape

(9, 1)

In [149]:
C.T

array([[4, 5, 6, 2, 1, 9, 0, 2, 8]])

In [150]:
R.T

array([[4],
       [5],
       [6],
       [2],
       [1],
       [9],
       [0],
       [2],
       [8]])

##### Square Matrix

In [153]:
def isSquareMatrix(M):
    if M.shape[0] == M.shape[1]:
        return True
    else:
        return False

In [154]:
M1.shape

(3, 3)

In [155]:
isSquareMatrix(M1)

True

In [156]:
isSquareMatrix(M)

False

In [160]:
S = np.zeros([4,4], dtype=np.int8)
S = S + 4

In [161]:
S

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]], dtype=int8)

##### Rectangular Matrix

In [163]:
def isRectangularMatrix(M):
    if M.shape[0] != M.shape[1]:
        return True
    else:
        return False

In [164]:
isRectangularMatrix(M1)

False

##### Diagonal Matrix

In [168]:
D = np.zeros([4,4], dtype=np.int8)
for i in range(4):
    D[i][i] = 4

D

array([[4, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 4]], dtype=int8)

In [177]:
def isDiagonalMatrix(M):
    for i in range(M.shape[0]):
        for j in range(M.shape[1]):
            if i != j and M[i][j] != 0:
                return False
    return True

In [178]:
isDiagonalMatrix(D)

True

In [179]:
isDiagonalMatrix(M)

False

##### Identity Matrix

In [182]:
I = np.zeros([4,4], dtype=np.int8)
for i in range(4):
    I[i][i] = 1

I

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8)

In [183]:
np.diag(I)

array([1, 1, 1, 1], dtype=int8)

##### Symmetric Matrix

In [196]:
S1 = np.array([[2,3,6],[3,4,5],[6,5,9]])
S1

array([[2, 3, 6],
       [3, 4, 5],
       [6, 5, 9]])

In [198]:
(S1 == S1.T).sum()

9

In [199]:
S1.size

9

In [200]:
def isSymmetricMatrix(M):
    if (M == M.T).sum() == M.size:
        return True
    else:
        return False

In [201]:
isSymmetricMatrix(S1)

True

In [203]:
isSymmetricMatrix(M1)

False

##### Skew-Symmetric Matrix

In [205]:
S2 = np.array([[0, 3],[-3, 0]])

In [206]:
S2

array([[ 0,  3],
       [-3,  0]])

In [207]:
-S2

array([[ 0, -3],
       [ 3,  0]])

In [208]:
S2.T

array([[ 0, -3],
       [ 3,  0]])

#### EigenVectors and Eigenvalues

In [232]:
# Define a matrix
A = np.array([[-6, 3], [4, 5]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print the eigenvalues
print("Eigenvalues:\n", eigenvalues)

# Print the eigenvectors (one per column)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues:
 [-7.  6.]
Eigenvectors:
 [[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]


In [235]:
A @ eigenvectors = 

array([[ True,  True],
       [False, False]])

array([[ 6.64078309, -1.45521375],
       [-2.21359436, -5.820855  ]])